development:
  adapter: sqlite3
  encoding: utf8
  database: shortened_urls_dev.sqlite, visits_dev.sqlite

test:
  adapter: sqlite3
  encoding: utf8
  database: shortened_urls_test.sqlite, visits_dev.sqlite

production:
  adapter: sqlite3
  encoding: utf8
  database: shortened_urls_live.sqlite, visits_dev.sqlite